apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: volume-nfs-sc
provisioner: nfsexport.rafflescity.io
reclaimPolicy: Delete
parameters:
  nfsExporterImage: daocloud.io/piraeus/volume-nfs-exporter:ganesha
  backendStorageClass: local-path
  # backendStorageClass: piraeus-local-dflt-r2
