apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumeexports.nfs.volume.io
spec:
  group: nfs.volume.io
  names:
    kind: VolumeExport
    listKind: VolumeExportList
    plural: volumeexports
    shortNames:
    - pve
    singular: volumeexport
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Data Volume
      jsonPath: .spec.dataVolume
      name: data volume
      type: string
    - description: NFS Export
      jsonPath: .spec.nfsExport
      name: nfs export
      type: string
    - description: Age
      jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VolumeExport is the Schema for the volumeexport
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: LocalVolumeMigrateSpec defines the desired state of LocalVolumeMigrate
            properties:
              dataVolume:
                type: string
              nfsExport:
                type: string
            required:
            - dataVolume
            - nfsExport
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
# apiVersion: nfs.volume.io/v1alpha1
# kind: VolumeExport
# metadata:
#   name: alex
# spec:
#   dataVolume: me
#   nfsExport: help
