kind: Namespace
apiVersion: v1
metadata:
  name: volume-nfs-export
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volume-nfs-provisioner
  namespace: volume-nfs-export
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volume-nfs-provisioner
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volume-nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: volume-nfs-provisioner
    namespace: volume-nfs-export
roleRef:
  kind: ClusterRole
  name: volume-nfs-provisioner
  apiGroup: rbac.authorization.k8s.io