# this is an example, using piraeus block storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-local-dflt-r2
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  layerlist: drbd storage
  placementCount: "2"
  placementPolicy: FollowTopology
  allowRemoteVolumeAccess: "false"
  disklessOnRemaining: "false"
  mountOpts: noatime,discard
  storagePool: DfltStorPool