kind: Namespace
apiVersion: v1
metadata:
  name: volume-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${data_pvc}
  namespace: volume-nfs
spec:
  storageClassName: ${data_sc}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${size}