apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumeexports.nfsexport.rafflescity.io
spec:
  group: nfsexport.rafflescity.io
  names:
    kind: VolumeExport
    listKind: VolumeExportList
    plural: volumeexports
    singular: volumeexport
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Backend Data VolumeClaim
      jsonPath: .spec.backendVolumeClaim
      name: data volume claim
      type: string
    - description: NFS Export
      jsonPath: .spec.nfsExport
      name: nfs export
      type: string
    - description: Age
      jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VolumeExport is the Schema for the VolumeExport
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: LocalVolumeMigrateSpec defines the desired state of LocalVolumeMigrate
            properties:
              backendVolumeClaim:
                type: string
              nfsExport:
                type: string
            required:
            - backendVolumeClaim
            - nfsExport
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: nfsexport.rafflescity.io/v1alpha1
kind: VolumeExport
metadata:
  name: iam
spec:
  backendVolumeClaim: not
  nfsExport: here
